name: ICRA
channels:
  - kne
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - autopep8=1.4.4=py_0
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=1
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35he75722e_1
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.6.0=cuda9.0_0
  - cycler=0.10.0=py35hc4d5149_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.5=281
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py35hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.0.0=py35h5429711_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35h7dd41cf_0
  - mkl_random=1.0.1=py35h4414c95_1
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py35h6bb024c_1
  - numpy-base=1.15.2=py35h81de0dd_0
  - openssl=1.0.2t=h7b6447c_1
  - pcre=8.43=he6710b0_0
  - pip=10.0.1=py35_0
  - pybox2d=2.3.1post2=py35_0
  - pycodestyle=2.4.0=py35_0
  - pycparser=2.19=py35_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py35h05f1152_2
  - python=3.5.6=hc3d631a_0
  - python-dateutil=2.7.3=py35_0
  - pytorch=0.4.1=py35ha74772b_0
  - pytz=2019.2=py_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - rope=0.14.0=py_0
  - setuptools=40.2.0=py35_0
  - sip=4.19.8=py35hf484d3e_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py35h7b6447c_0
  - wheel=0.31.1=py35_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cloudpickle==1.2.1
    - cython==0.29.12
    - future==0.17.1
    - gym==0.13.1
    - numpy==1.16.4
    - pyglet==1.3.2
    - scipy==1.3.0
    - six==1.12.0
prefix: /home/zhaozj/.conda/envs/ICRA

